apiVersion: 1

datasources:
- name: My InfluxDB Server
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  user: admin
  password: admin
  database: oanda
  isDefault: true
  editable: false
  version: 1
